### ISSUE TITLE
Where are the label distances?

### ISSUE THREAD

**Issue by raymongL** [tjddus9597/Beyond-Binary-Supervision-CVPR19#1]
Hi, thanks for sharing the code, marvelous work! 
Just read the paper, and i'm confused about the label distances mentioned in the paper, so i github the code and find this page. So in the code, label distances, i.e. gt_dist, comes from dataloader? But I couldn't find the exact code that gives the gt_dist. 

After reading the paper i'm quite confused what exactly is 'label distance', and how to compute it? 
Again, thanks for sharing and brilliant insight into the continuous labels!

**Comment by tjddus9597** [comment]
Sorry for late reply. I noticed this issue too late.
First, thank you for reading my paper.

'gt_dist' comes from getitem in Dense_PairDataset(or Naive_PairDataset).
In 'Dense_PairDataset' class, 'gt_dist' is called dist_pairs which is loaded from 'dist_nn.pkl'

'dist_nn.pkl' and 'list_nn.pkl' can be downloaded from here [https://drive.google.com/file/d/1_KJw9wD1WEjproxuNQf2M9J3JamTt9WD/view]
And this file is already computed from labels of MPII dataset.

In this task, label distance between two poses is the sum of Euclidean distances between body-joint locations which are represented as vectors. And that labels have 16 coordinates of a joint(.x, .y) in each pose image.

If you have any other question, please comment. :D

**Comment by raymongL** [comment]
Thanks a lot! You've made a very clear description, it helps a lot!

**Comment by reacher-l** [comment]
hello，My friend, do you know what oracle is in the article?

**Comment by tjddus9597** [comment]
> hello，My friend, do you know what oracle is in the article?

Hi, my friend. :)
Oracle is upper-bound of performance. For example, an oracle in a 'mean distance' measure is the performance of a perfect retrieve for all queries. The oracle is specified to show the gap between our model's performance and the upper-bound for each dataset. Because our paper was the first attempt to deal with continuous labels in deep metric learning.
One may notice that the oracle in mean nDCG is 1.

If you have any other question, please comment. :D

**Comment by reacher-l** [comment]
Your answers were very clear. It was a great job. Thank you very much for your contribution

**Comment by reacher-l** [comment]
> > hello，My friend, do you know what oracle is in the article?
> 
> Hi, my friend. :)
> Oracle is upper-bound of performance. For example, an oracle in a 'mean distance' measure is the performance of a perfect retrieve for all queries. The oracle is specified to show the gap between our model's performance and the upper-bound for each dataset. Because our paper was the first attempt to deal with continuous labels in deep metric learning.
> One may notice that the oracle in mean nDCG is 1.
> 
> If you have any other question, please comment. :D

Your answers were very clear. It was a great job. Thank you very much for your contribution
